//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace PrinterResearch {
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/PrintersSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/PrintersSchema.xsd", IsNullable=false)]
    public partial class printers {
        
        private ObservableCollection<printersPrinter> printerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("printer")]
        public ObservableCollection<printersPrinter> printer {
            get {
                return this.printerField;
            }
            set {
                this.printerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/PrintersSchema.xsd")]
    public partial class printersPrinter {
        
        private string makeField;

        private string modelField;

        private string hrefField;

        private string yieldField;
        
        private string inkCostField;
        
        private sbyte listPriceField;
        
        private sbyte otherPriceField;
        
        private printersPrinterDimensions dimensionsField;
        
        private string touchScreenField;
        
        private short volumeField;
        
        private string notesField;
        
        /// <remarks/>
        public string Make {
            get {
                return this.makeField;
            }
            set {
                this.makeField = value;
            }
        }

        /// <remarks/>
        public string Model
        {
            get
            {
                return this.modelField;
            }
            set
            {
                this.modelField = value;
            }
        }

        /// <remarks/>
        public string Href
        {
            get
            {
                return this.hrefField;
            }
            set
            {
                this.hrefField = value;
            }
        }

        /// <remarks/>
        public string Yield {
            get {
                return this.yieldField;
            }
            set {
                this.yieldField = value;
            }
        }
        
        /// <remarks/>
        public string InkCost {
            get {
                return this.inkCostField;
            }
            set {
                this.inkCostField = value;
            }
        }
        
        /// <remarks/>
        public sbyte ListPrice {
            get {
                return this.listPriceField;
            }
            set {
                this.listPriceField = value;
            }
        }
        
        /// <remarks/>
        public sbyte OtherPrice {
            get {
                return this.otherPriceField;
            }
            set {
                this.otherPriceField = value;
            }
        }
        
        /// <remarks/>
        public printersPrinterDimensions Dimensions {
            get {
                return this.dimensionsField;
            }
            set {
                this.dimensionsField = value;
            }
        }
        
        /// <remarks/>
        public string TouchScreen {
            get {
                return this.touchScreenField;
            }
            set {
                this.touchScreenField = value;
            }
        }
        
        /// <remarks/>
        public short Volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
        
        /// <remarks/>
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/PrintersSchema.xsd")]
    public partial class printersPrinterDimensions {
        
        private sbyte widthField;

        private sbyte depthField;

        private sbyte heightField;
        
        /// <remarks/>
        public sbyte Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public sbyte Depth {
            get {
                return this.depthField;
            }
            set {
                this.depthField = value;
            }
        }
        
        /// <remarks/>
        public sbyte Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
    }
}
